# Generated by Django 5.0.7 on 2024-09-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
