# Generated by Django 5.0.7 on 2024-09-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_artical_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
