# Generated by Django 5.0.7 on 2024-09-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_artical_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
